### ISSUE TITLE
Cannot install due to security-advisory check

### ISSUE THREAD

**Issue by sirbrillig** [sirbrillig/phpcs-variable-analysis#10]
When I try to run `composer install` on a package that requires this package, I get the following error:

```
    - sirbrillig/phpcs-variable-analysis dev-master requires roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master] but these conflict with your requirements or minimum-stability.
```

This was introduced in #5 

To reproduce, have a composer.json with these requirements:

```
    "require-dev": {
        "sirbrillig/phpcs-variable-analysis": "dev-master"
    }
```

**Comment by sirbrillig** [comment]
ping @GaryJones because I'm not clear why this is showing up.

**Comment by sirbrillig** [comment]
Hm... Maybe it's [this conflict](https://github.com/Roave/SecurityAdvisories/blob/master/composer.json#L71) with php_codesniffer itself. We require 3.0.2, so it's not us. Could it be that phpcodesniffer-composer-installer [requires `*`](https://github.com/DealerDirect/phpcodesniffer-composer-installer/blob/master/composer.json#L29)? 🤔

**Comment by GaryJones** [comment]
Either this project or your consuming project, will likely need:

```json
    "minimum-stability": "dev",
    "prefer-stable": true,
```
 in the `composer.json`.

**Comment by sirbrillig** [comment]
Thanks for figuring that out. TIL. From testing it looks like it's necessary to add it to both this project _and_ the consuming project. I'll add a note in the README, since those fields are not automatically added by `composer init` and so I wouldn't be surprised if other people run into this as well.

**Comment by sirbrillig** [comment]
At the moment, I find requiring the `minimum-stability` field is too much of a burden on developers who just want to include this standard, so I've removed the `roave/security-advisories` package for now.
