### ISSUE TITLE
Report undefined/unused variables only inside functions

### ISSUE THREAD

**Issue by ghnp5** [sirbrillig/phpcs-variable-analysis#125]
Is it possible, or could it be possible in the future, to disable undefined/unused checks against variables outside functions?

I get a lot of false positives on files where variables are defined under "required/included" files, or in files that are themselves "required/included" by other files.

However, inside functions, it is much easier/accurate to find undefined/unused variables, and those are the places I'm particularly interested anyway.

This is what PHP Intelephense extension in VSCode does.
I just would like to do the same on the builds, using PHPCS.

Thank you very much.

**Comment by sirbrillig** [comment]
That's a good idea.

**Comment by ghnp5** [comment]
Thank you very much.
Unfortunately, I'll have to keep this extension disabled (because it reports too much noise) but please do update me here when this is implemented! I'd love to have this extension in action :)

**Comment by sirbrillig** [comment]
Revisiting this as we get close to 3.0.

> This is what PHP Intelephense extension in VSCode does.

Just to clarify, would an option that disabled scanning of the file-scope solve your issue?

If you have a chunk of code that I could use an example of the warnings you'd prefer not to see, it would be very helpful.

**Comment by ghnp5** [comment]
Thank you for this.

See screenshot below:

![image](https://user-images.githubusercontent.com/57591332/87387053-cf7d8780-c599-11ea-9bc3-8d2f7ae33826.png)


PHP Intelephense works great for VSCode, to find me variables that are undefined/unused while I'm coding.

What I want is to automate these checks also when I build my code, through PHPCS.


Your extension does this, but it's also complaining about variables outside functions.
If I could disable the checks for variables that are NOT inside functions, that would be great!

So, I wouldn't want PHPCS to warn about the "$test" at the end of the screenshot above.

Thank you very much.

**Comment by sirbrillig** [comment]
Thank you! It should be fixed by https://github.com/sirbrillig/phpcs-variable-analysis/pull/193 which will be included in version 3.0.

**Comment by ghnp5** [comment]
@sirbrillig - Has this been released yet? I see there's no version 3 yet, but the PR was merged to master, several months ago. Is "master" not what's released, but will be version 3, is that it? Thank you very much!

**Comment by sirbrillig** [comment]
Hi! It's a little confusing. Due to the instability of one of the dependencies of 3.0, I've backported nearly all the features into the 2.x branch starting with 2.10.0, which includes the `allowUndefinedVariablesInFileScope` option (see release notes at https://github.com/sirbrillig/phpcs-variable-analysis/releases/tag/v2.10.0). The latest released version, [2.10.2](https://github.com/sirbrillig/phpcs-variable-analysis/releases/tag/v2.10.2), also includes this option.

**Comment by ghnp5** [comment]
@sirbrillig - Thank you very much. I should have asked earlier!! 😂😂👍
