### ISSUE TITLE
Unused parameters in methods in abstract classes

### ISSUE THREAD

**Issue by jrfnl** [sirbrillig/phpcs-variable-analysis#133]
Abstract classes can contain abstract methods which are _required_ to be overloaded, but they can also contain empty methods which are _optional_ to overload.

```php
abstract class Foo
{
    // Required to be overloaded.
    abstract public function bar($param);

    // Optional to be overloaded.
    public function baz($param) {
    }
}
```

This standard will throw a `Unused function parameter $param.(VariableAnalysis.CodeAnalysis.VariableAnalysis.UnusedVariable)` warning for the second method `bax()`.

While technically correct, IMHO it would be sane to make an exception for these kind of "optional overload" (empty) methods in `abstract` classes.

**Comment by sirbrillig** [comment]
I agree. Maybe something like "if the variable is an argument of a function that is a method of an abstract class and the method body is empty, then do not mark unused".

**Comment by jrfnl** [comment]
Just thinking - maybe it should be: ""if the variable is an argument of a function that is a method of an abstract class and the method body is empty _on only contains `return;`_, then do not mark unused"."

**Comment by lkraav** [comment]
Indeed, I think I'm running into an abstract class method defined as `abstract public function decompress( $compressed_item, $compressed_data_layer );`, where we don't use `$compressed_data_layer`, but need to include it to match overload signature.
