### ISSUE TITLE
Package dependency breaks stand-alone installation

### ISSUE THREAD

**Issue by titpetric** [sirbrillig/phpcs-variable-analysis#160]
After following standalone installation instructions, the following error pops up when running phpcs.

PHP Fatal error:  Uncaught Error: Class 'PHPCSUtils\Utils\Lists' not found in /usr/local/bin/VariableAnalysis/VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php:869

**Comment by sirbrillig** [comment]
Thanks for pointing that out! I didn't consider that adding a dependency package means that installing without composer will not work. I'll figure out a solution but in the mean time if you want to do a standalone install, use the latest release version instead: https://github.com/sirbrillig/phpcs-variable-analysis/releases/tag/v2.8.1

**Comment by jrfnl** [comment]
@sirbrillig See https://github.com/PHPCSStandards/PHPCSUtils/#non-composer-based-integration for more extensive information.

Short summary: if you still want to support stand-alone installs, two steps are needed:
1. The user has to run `composer install` in the VariableAnalysis package root directory or install PHPCSUtils separately as a stand-alone package too.
2. When setting the `installed_paths`, both the paths to the `VariableAnalysis` as well as to `PHPCSUtils` need to be added.

As long as both those steps are followed, using a `git clone` or other stand-alone install of `VariableAnalysis` should work fine.

**Comment by sirbrillig** [comment]
(FTR I modified the readme for now to point to the most recent release in #161 )

**Comment by sirbrillig** [comment]
This was fixed by https://github.com/sirbrillig/phpcs-variable-analysis/pull/177
