### ISSUE TITLE
VariableAnalysis\Tests\VariableAnalysisTest autoloading deprecation in Composer 2.0

### ISSUE THREAD

**Issue by rutek** [sirbrillig/phpcs-variable-analysis#162]
Recent version of Composer generates following deprecation notice for your package:

```
Deprecation Notice: Class VariableAnalysis\Tests\VariableAnalysisTest located in ./vendor/sirbrillig/phpcs-variable-analysis/VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///workspace/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
```

Your test file https://github.com/sirbrillig/phpcs-variable-analysis/blob/master/VariableAnalysis/Tests/CodeAnalysis/VariableAnalysisTest.php should be in `VariableAnalysis\Tests\CodeAnalysis` namespace according to psr-4.

**Comment by jrfnl** [comment]
Thanks for reporting this. PR #164 should take care of this.
