### ISSUE TITLE
Support PHP 7.4

### ISSUE THREAD

**Issue by sirbrillig** [sirbrillig/phpcs-variable-analysis#165]
This is a meta issue to make sure we support PHP 7.4 ([changes](https://www.php.net/releases/7_4_0.php))

- Arrow functions: https://github.com/sirbrillig/phpcs-variable-analysis/issues/134
- Add CI build

**Comment by jrfnl** [comment]
Some additions to verify if these are supported/need support:
* If at any point the sniff looks at numbers: numeric literals with underscore separators
* Typed properties

FYI: PHPCSUtils has helper functions which already handle PHP 7.4 correctly for each of these + arrow functions.

**Comment by kkmuffme** [comment]
Just wanted to inquire if PHP7.4 is supported now?

**Comment by sirbrillig** [comment]
I think the main thing we need is support for arrow functions, which I started working on in https://github.com/sirbrillig/phpcs-variable-analysis/pull/179 but I got kind of stuck. Handling implicit closure scope turns out to be complicated. Suggestions and assistance on that PR are welcome!

**Comment by sirbrillig** [comment]
Closed by #179
