### ISSUE TITLE
phpcs: Referenced sniff "VariableAnalysis" does not exist

### ISSUE THREAD

**Issue by kurdtpage** [sirbrillig/phpcs-variable-analysis#169]
I installed this using the instructions in the readme using 
`composer require --dev sirbrillig/phpcs-variable-analysis`
and it comes up with:
> phpcs: Referenced sniff "VariableAnalysis" does not exist

In phpcs.xml, I have: `<rule ref="VariableAnalysis"/>`
I also tried `<rule ref="VariableAnalysis.CodeAnalysis.VariableAnalysis"/>` but it comes up with the same ("...does not exist").

I am using PHP 7.4, PHPCS 3.5.5 and phpcs-variable-analysis 2.8.1

**Comment by jrfnl** [comment]
@kurdtpage Did you follow the install instructions completely ? I.e. did you also run `composer require --dev dealerdirect/phpcodesniffer-composer-installer` ?

If not: try that first as that plugin should typically prevent the issue you are seeing.

**Comment by truongwp** [comment]
@kurdtpage Probably you run system `phpcs`. Make sure that you run `phpcs` from composer vendor like this: `./vendor/squizlabs/php_codesniffer/bin/phpcs`

**Comment by kurdtpage** [comment]
In settings.json, phpcs.executablePath was set to "C:\\\Users\\\kurdtpage\\\AppData\\\Roaming\\\Composer\\\vendor\\\bin\\\phpcs". I changed this path, installed the phpcs installer and now there are no errors, except for my own :-)
> Variable $db is undefined

Thank you both so much
