### ISSUE TITLE
Unused variable Being Flagged but its being Used inside the While loop

### ISSUE THREAD

**Issue by darthvader666uk** [sirbrillig/phpcs-variable-analysis#224]
Hi,

Wondered if you could help?

I couldn't see a relevant issue open to what I am seeing but basically when declaring the variable `$bytes_read = 0;`, it flags as unused even though we are using it inside a while loop.  This is the full code:

```
		if ($handle = fopen($file_path, "rb")) {
			if ($file_offset > 0) fseek($handle, $file_offset);
			$bytes_read = 0;
			while ($file_bytes > 0 && $read = fread($handle, max($file_bytes, 131072))) {
				$file_bytes = $file_bytes - strlen($read);
				$bytes_read += strlen($read);
				$data .= $read;
			}
			fclose($handle);
		} else {
			return false;
		}
```

As you can see `$bytes_read` is used again inside the while loop.  The ONLY thing I can think is why its flagging is because `$bytes_read` isn't used outside the while but why would it flag  `$bytes_read = 0;`?

**Comment by sirbrillig** [comment]
Thanks for the example! That can be confusing for sure, but the reason it's marking `$bytes_read` as unused is that nothing is ever done with the variable. It's initialized to `0`, then it's modified, but that's it. Removing the variable entirely would not change the code. If you added something like `return $bytes_read;`, or `echo $bytes_read;`, then the warning should disappear. Does that make sense? It's not being "used" in the sense that it's never read, only written to.

**Comment by sirbrillig** [comment]
I'm going to close this for the moment, but if you have any further questions, please feel free to re-open it!
