### ISSUE TITLE
Update phpcs version in composer.json

### ISSUE THREAD

**Issue by coccoinomane** [sirbrillig/phpcs-variable-analysis#226]
Hello,
[Version 3.6 of PHPCS](https://github.com/squizlabs/PHP_CodeSniffer/issues/3167) added supports to the Property Promotion feature from [PHP8](https://stitcher.io/blog/constructor-promotion-in-php-8).
Would it be possible to update the version of the dependency in composer.json? It is currently 3.5.0.
Thanks,
Guido

**Comment by jrfnl** [comment]
@coccoinomane Two things here:

1. PHPCS 3.6.0 has not yet been released.
2. The dependency version in `composer.json` is set up as a "minimum version" requirement, so as long as _your own_ `composer.json` doesn't prohibit it, PHPCS 3.6.0 will be installed for VA once it has been released.

https://github.com/sirbrillig/phpcs-variable-analysis/blob/0775e0c683badad52c03b11c2cd86a9fdecb937a/composer.json#L43

**Comment by jrfnl** [comment]
Also note: updating to PHPCS 3.6.0 doesn't magically add support for PHP 8 features to the sniff in this repo. That will still potentially need additional work.

**Comment by sirbrillig** [comment]
TIL about this RFC. That's very cool! Yeah, we'll need to add special logic to handle this since (besides probably breaking something) it will appear that such variables are unused parameters in the constructor.

**Comment by sirbrillig** [comment]
I created https://github.com/sirbrillig/phpcs-variable-analysis/issues/227 to track supporting this new feature.

**Comment by coccoinomane** [comment]
Thank you @sirbrillig for the clarification, it's all clear now 👍
I'll wait for the feature to be implemented.
Have a nice day,
Guido
