### ISSUE TITLE
Handle constructor promotion

### ISSUE THREAD

**Issue by sirbrillig** [sirbrillig/phpcs-variable-analysis#227]
Constructor promotion (https://stitcher.io/blog/constructor-promotion-in-php-8) allows code like the following:

```php
class MyDTO
{
    public function __construct(
        public string $name = 'Brent',
    ) {}
}
```

But this sniff will mark `$name` unused and it is in fact used. We'll need to handle that.

This was extracted from https://github.com/sirbrillig/phpcs-variable-analysis/issues/226

**Comment by jrfnl** [comment]
For information on how support was implemented in PHPCS (via the `File::getMethodParameters()` method): https://github.com/squizlabs/PHP_CodeSniffer/pull/3152

The same was already available via PHPCSUtils via `FunctionDeclarations::getParameters()` and the implementation in PHPCSUtils is backward compatible all the way back to PHPCS 2.6.0.
See: https://github.com/PHPCSStandards/PHPCSUtils/pull/169
