### ISSUE TITLE
Support constructor promotion with readonly properties (UnusedVariable)

### ISSUE THREAD

**Issue by defunctl** [sirbrillig/phpcs-variable-analysis#290]
The following throws this error: 

`phpcs: VariableAnalysis.CodeAnalysis.VariableAnalysis.UnusedVariable: Unused function parameter $message.`

```php
<?php declare(strict_types=1);

namespace MyProject;

final class Manager {

	public function __construct(
		private readonly string $message
	) {}

	public function getMessage(): string {
		return $this->message;
	}

}
```

PHP Version: 8.1
Variable Analysis Version: v2.11.10

**Comment by sirbrillig** [comment]
Interesting! Constructor promotion support was added in https://github.com/sirbrillig/phpcs-variable-analysis/pull/266 but I bet that the `readonly` token could be breaking the logic.

**Comment by jrfnl** [comment]
@sirbrillig FYI, in case it helps: the PHPCS native `File::getMethodParameters()` method [has support for both](https://github.com/squizlabs/PHP_CodeSniffer/blob/add95a74551c3ba8fc99ef7651ad05f553b3fbbf/src/Files/File.php#L1311-L1315), but using that would require some changes in how things are being sniffed (or detection of a function declaration based on the parentheses surrounding parameters and using the method that way).

**Comment by jrfnl** [comment]
Just ran into this one myself now ;-)

**Comment by sirbrillig** [comment]
https://github.com/sirbrillig/phpcs-variable-analysis/pull/294 should fix this.

**Comment by jrfnl** [comment]
Much appreciated @sirbrillig !
