### ISSUE TITLE
method call called 'enum' causes an "Cannot find enum start at position" error

### ISSUE THREAD

**Issue by Levivb** [sirbrillig/phpcs-variable-analysis#292]
Hey, 

Running the code sniffer over the following code causes an error

```
<?php

declare(strict_types=1);

namespace App\Auth;

final class Test
{
    public function __construct(private readonly SomcClass $someClass)
    {
    }

    public function createFor()
    {
        $this->someClass->enum('test');
    }
}
```

The error message:
` 1 | ERROR | An error occurred during processing; checking has been aborted. The error message was: Cannot find enum start at position 67`

It seems the bug was introduced in https://github.com/sirbrillig/phpcs-variable-analysis/pull/289

It looks like 'enum' method calls are not handled correctly :)

**Comment by sirbrillig** [comment]
Thanks for noticing this! I figured I had missed something.

**Comment by Levivb** [comment]
Thanks for the insanely quick fix! 👍
