### ISSUE TITLE
Unused function parameter in lambda function

### ISSUE THREAD

**Issue by ghnp5** [sirbrillig/phpcs-variable-analysis#295]
Consider this code:

`$type = in_array_cb($_GET['type'], TYPES, fn(&$array, $needle) => $array[2] === $needle);`

The parameter `$needle` is marked as an error:

> Unused function parameter $needle.PHPCS(VariableAnalysis.CodeAnalysis.VariableAnalysis.UnusedVariable)

<img width="265" alt="image" src="https://user-images.githubusercontent.com/57591332/228976175-b4508add-7c3a-43e3-9b85-6ce5b47e8025.png">

**Comment by sirbrillig** [comment]
Interesting! It looks like something to do with the array access which is breaking this. The bug does occur in the expression:

```
do_something(fn($array, $needle) => $array[2] === $needle);
```

But it does not occur in:

```
do_something(fn($array, $needle) => $array === $needle);
```

I think that there's a bug in how we detect the scope of an arrow function which contains a bracket.

**Comment by sirbrillig** [comment]
https://github.com/sirbrillig/phpcs-variable-analysis/pull/296 should fix this.

**Comment by ghnp5** [comment]
Thanks @sirbrillig  - that was a quick fix & release!!
Working perfectly now.

**Comment by sirbrillig** [comment]
Turns out the fix was really easy: just stop letting phpcs do its own scope detection for arrow functions. 😁
