### ISSUE TITLE
Undefined variable error introduced in v2.11.15

### ISSUE THREAD

**Issue by srtfisher** [sirbrillig/phpcs-variable-analysis#300]
Hi 👋 

I happened to upgrade to v2.11.15 just now and PHPCS is reporting an undefined variable for case where a variable is defined. Here's an example:

https://gist.github.com/srtfisher/920bdcbfc4acde5b4c2bb17c9d3f5d30

In that gist L20 only throws the error. It seems defined on L18 and L23.

Thank you!

**Comment by sirbrillig** [comment]
ah, TIL that arrow functions can contain newlines. whoops. Should be fixed shortly.

**Comment by srtfisher** [comment]
Thank you!
