### ISSUE TITLE
`squizlabs/PHP_CodeSniffer` is abandoned - Replace with `PHPCSStandards/PHP_CodeSniffer` when the time is right

### ISSUE THREAD

**Issue by Levivb** [sirbrillig/phpcs-variable-analysis#314]
See https://github.com/squizlabs/PHP_CodeSniffer/issues/3932

Will this package switch to https://github.com/PHPCSStandards/PHP_CodeSniffer as it is a direct fork?

Given jrfnl's activity a few days ago (https://github.com/sirbrillig/phpcs-variable-analysis/commit/151bed47c4340ff00436ae5de3d1f4225cfeb3bb) I suspect this package will not be overlooked. 

But wanted to mention it here to get a bit of a headstart :)

Looks like it will be a drop-in replacement once the replacement package will get a new tag

**Comment by jrfnl** [comment]
@Levivb The branch was already pushed, just not pulled yet...

**Comment by Levivb** [comment]
You are truly on top of everything 🥇

**Comment by Levivb** [comment]
https://github.com/squizlabs/PHP_CodeSniffer/issues/3932#issuecomment-1842531678

no change is needed. Closing this issue :)
