### ISSUE TITLE
Handle constructor promotion with Nullable types

### ISSUE THREAD

**Issue by yokozawa0701** [sirbrillig/phpcs-variable-analysis#320]
I want to use Nullable types in a constructor promotion like following.

```php
public function __construct(
    public ?string $name,
) {}
```

But it showed `Unused function parameter $name. (VariableAnalysis.CodeAnalysis.VariableAnalysis.UnusedVariable)` .
Is it possible to use like this?

**Comment by sirbrillig** [comment]
In theory that was handled by https://github.com/sirbrillig/phpcs-variable-analysis/pull/266 and https://github.com/sirbrillig/phpcs-variable-analysis/issues/290 but I wouldn't be surprised if there's a bug with nullable types. I'll try to fix it.

**Comment by yokozawa0701** [comment]
Thank you so much!
