### ISSUE TITLE
Unexpected slowness since `v2.11.20`

### ISSUE THREAD

**Issue by AronNovak** [sirbrillig/phpcs-variable-analysis#340]
There are some linting CI jobs that typically finishes under 2 minutes, after `v2.11.20`, those do timeout after 10 minutes.
```
[0K$ $TRAVIS_BUILD_DIR/ci-scripts/install_coder.sh || travis_terminate 1;
Changed current directory to /home/travis/.config/composer
Changed current directory to /home/travis/.config/composer
./composer.json has been updated
Running composer update drupal/coder
Loading composer repositories with package information
Updating dependencies
Lock file operations: 9 installs, 0 updates, 0 removals
  - Locking dealerdirect/phpcodesniffer-composer-installer (v1.0.0)
  - Locking drupal/coder (8.3.25)
  - Locking phpstan/phpdoc-parser (1.33.0)
  - Locking sirbrillig/phpcs-variable-analysis (v2.11.20)
  - Locking slevomat/coding-standard (8.15.0)
  - Locking squizlabs/php_codesniffer (3.11.1)
  - Locking symfony/deprecation-contracts (v2.5.4)
  - Locking symfony/polyfill-ctype (v1.31.0)
  - Locking symfony/yaml (v5.4.45)
Writing lock file
```

We use it via https://www.drupal.org/project/coder, downgrading this library fixes the slowness.

**Comment by AronNovak** [comment]
I could reproduce it at an open source repository.

https://app.travis-ci.com/github/Gizra/drupal-starter/jobs/628615001
https://github.com/Gizra/drupal-starter/pull/765

And the previously working state:
https://app.travis-ci.com/github/Gizra/drupal-starter/jobs/628508111

**Comment by AronNovak** [comment]
So from 69 seconds, the execution time jumped to 325 seconds in this case, for this simple starter kit project.

**Comment by mpifalo** [comment]
Can confirm we encountered that same timeout after updating our Drupal project this morning. Setting a conflict in composer.json and we no longer have the timeout in CI:

```
    "conflict": {
        "sirbrillig/phpcs-variable-analysis": "2.11.20"
    }
```

**Comment by sirbrillig** [comment]
Investigating. There were four changes since 2.11.19. Trying to determine which one caused this:

- https://github.com/sirbrillig/phpcs-variable-analysis/pull/339
- https://github.com/sirbrillig/phpcs-variable-analysis/pull/337
- https://github.com/sirbrillig/phpcs-variable-analysis/pull/334
- https://github.com/sirbrillig/phpcs-variable-analysis/pull/333

Update: It's definitely this one:

- https://github.com/sirbrillig/phpcs-variable-analysis/pull/334

Working on a fix.

**Comment by sirbrillig** [comment]
Should be fixed by https://github.com/sirbrillig/phpcs-variable-analysis/pull/342

**Comment by sirbrillig** [comment]
Thanks for the reports, everyone! 2.11.21 should fix this issue.

I made an issue (https://github.com/sirbrillig/phpcs-variable-analysis/issues/343) to add a guard to prevent this happening again.

**Comment by mpifalo** [comment]
Awesome; thanks for the quick turnaround. Can confirm that with 2.11.21 CI is just as fast as before. TY!
