### ISSUE TITLE
Needs performance guard CI process

### ISSUE THREAD

**Issue by sirbrillig** [sirbrillig/phpcs-variable-analysis#343]
We need to add a CI task that guards against major performance regressions like https://github.com/sirbrillig/phpcs-variable-analysis/issues/340

**Comment by jrfnl** [comment]
Not sure if it would help, but PHPCS itself offers a Performance report `--report=Performance` and you could possibly parse the outcome of that to check against a threshold value ?
The report is most interesting when combined with a range of sniffs to see which ones in a particular ruleset are performance hogs, but I suppose it could also be used for this.

As for _improving_ performance, PHPCSUtils can help with that as any repeated calls to utility functions with the same arguments will get cached results within a single runtime (for most functions), which can often save a lot of processing.

**Comment by jrfnl** [comment]
Note: the Performance report is only available in PHPCS 3.8.0+.

**Comment by sirbrillig** [comment]
Ah, that's cool! 

Yeah, I'd like to just make a job that runs a timing check and makes sure that the total time is not greater than X. In this case, the performance before https://github.com/sirbrillig/phpcs-variable-analysis/pull/334 was about `0.528548` seconds as measured on my machine by `--report=Performance` and after that PR it was `66.230763` seconds (using [this file](https://raw.githubusercontent.com/WordPress/WordPress/refs/heads/master/wp-includes/PHPMailer/PHPMailer.php) as a benchmark). I think we could safely say that if the total is greater than around 0.6 seconds, CI should fail. I'll see if I can build something using that.

**Comment by jrfnl** [comment]
Maybe run `grep` over the output of the report ?

I'm thinking a variation of these steps (but then with phpcs & the Performance report, store the time output to `$GITHUB_OUTPUT` and compare that output then against a fixed setting in a next step): https://github.com/sirbrillig/phpcs-variable-analysis/blob/eb2b351927098c24860daa7484e290d3eed693be/.github/workflows/test.yml#L195-L214
