### ISSUE TITLE
Bug: Properties in traits are marked as undefined

### ISSUE THREAD

**Issue by Loilo** [sirbrillig/phpcs-variable-analysis#39]
Traits [can define](http://php.net/manual/en/language.oop5.traits.php#language.oop5.traits.properties) properties which are currently marked as undefined.

Example:
```php
trait JsonInjectable
{
    protected $jsonReader; // "Variable $jsonReader is undefined"
}
```

**Comment by sirbrillig** [comment]
Oo! Good catch. Created #40 to work on it.
