### ISSUE TITLE
Internal.Exception error

### ISSUE THREAD

**Issue by colis** [sirbrillig/phpcs-variable-analysis#46]
Hi,

I have the following error at the beginning of each PHP file:

```
[Internal.Exception] An error occurred during processing; checking has been aborted. The error message was: Argument 2 passed to VariableAnalysis\Lib\Helpers::findVariableScope() must be an instance of VariableAnalysis\Lib\int, integer given, called in /vendor/sirbrillig/phpcs-variable-analysis/VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php on line 670 and defined in /vendor/sirbrillig/phpcs-variable-analysis/VariableAnalysis/Lib/Helpers.php on line 167
```

I'm using the latest version of PHPCS.

Thanks.

**Comment by sirbrillig** [comment]
Hm... What version of PHP are you using? The [line in question](https://github.com/sirbrillig/phpcs-variable-analysis/blob/71cbcdbdb3ba03a0354a4ef01c219a6c750d20ab/VariableAnalysis/Lib/Helpers.php#L167) has `int` as an argument type which ... I just realized was a feature added in PHP 7, so I'm guessing you're using PHP 5. Dang, I'll have to bump the minimum version requirement in the composer configuration. Thanks for finding that and sorry for the confusion! In the mean time if you upgrade to PHP 7 the sniff should work as expected.

**Comment by sirbrillig** [comment]
It should be fixed now. 🤞

**Comment by colis** [comment]
thanks for the quick turnaround! yeah, I'm using an older version of PHP so I eventually noticed that typehints was the problem 🙂
