### ISSUE TITLE
Bug: Anonymous classes

### ISSUE THREAD

**Issue by Loilo** [sirbrillig/phpcs-variable-analysis#52]
This package currently seems not to be well-equipped for [anonymous classes](https://secure.php.net/manual/en/language.oop5.anonymous.php). 🙂

```php
$object = new class {
    public $foo; // "Variable $foo is undefined"

    public function __construct()
    {
        $this->foo = 'bar'; // "Variable $this" is undefined
    }
};
```

(Thanks for the great package by the way! I tend to get pretty mechanical when reporting bugs, but I really should sprinkle some gratefulness here and there. ❤️)

**Comment by Loilo** [comment]
I just realized that this is probably pretty closely related to #39. I'll take a look at the solution in #40 and try to prepare a pull request. 🙂

**Comment by sirbrillig** [comment]
Much appreciated!
