### ISSUE TITLE
Add option to allow specific variables

### ISSUE THREAD

**Issue by brandonkal** [sirbrillig/phpcs-variable-analysis#55]
I see that it is possible to allow certain variables to not be flagged if they are unused: https://github.com/sirbrillig/phpcs-variable-analysis#customization

I would love to have this same option for undefined variables. I am specifically interested in the $post variable, which is used liberally in the WordPress loop.

**Comment by sirbrillig** [comment]
That's a very good idea. Thank you for the issue and the implementation!
