### ISSUE TITLE
"BSD" is not a valid license identifier

### ISSUE THREAD

**Issue by GaryJones** [sirbrillig/phpcs-variable-analysis#6]
In `composer.json`, the `license` is given as `BSD`, but this is not valid. The value should be one of the values from https://spdx.org/licenses/, and as can be seen, there are several variations of "BSD".

**Comment by sirbrillig** [comment]
You're right! I was just trying to match [the license included in the original repo](https://github.com/illusori/PHP_Codesniffer-VariableAnalysis/blob/master/LICENSE), but this is the first time I've released something under that license and I didn't think to look for the specific one. It seems to be `BSD-2-Clause`.
