### ISSUE TITLE
Static member references in variable classes are marked as undefined

### ISSUE THREAD

**Issue by sirbrillig** [sirbrillig/phpcs-variable-analysis#62]
Originally reported in https://github.com/Automattic/phpcs-neutron-standard/issues/73 by @beaucollins 

The following example reports an undefined variable warning for `$static_member_var` when it should not:

```php
class ClassWithLateStaticBinding {
    public static $static_member_var;
    static function method_with_late_static_binding() {
        $called_class = get_called_class();
        echo $called_class::$static_member_var;
    }
}
```

**Comment by sirbrillig** [comment]
See also the changes made in #27

**Comment by beaucollins** [comment]
For completeness this is what `get_called_class()` does:

```php
static function get_called_class() {
  $called_class = static:class;
  // does some validation/reflection on $called_class
  return $called_class;
}
```

**Comment by beaucollins** [comment]
This isn't blocking, I was able to make a "workaround" that ultimately is a better solution by making a `static function get_model_schema()` function.
