### ISSUE TITLE
Variable variables are considered unused on assignment left-hand side

### ISSUE THREAD

**Issue by loilo** [sirbrillig/phpcs-variable-analysis#84]
Variable variables are considered unused when only appearing on the left-hand side of an assignment.

This is considered fine:

```php
function fn()
{
    $foo = true;
    $var = 'foo';
    return $$var;
}
```

While this says `$var` is unused:

```php
function fn()
{
    $foo = true;
    $var = 'foo';
    $$var = false;
}
```

(`$foo` is marked unused in both cases, but I guess there's no way to avoid that without deeper program flow analysis.)

**Comment by sirbrillig** [comment]
Thanks! Wow, variable variables are tough. I created #87 to track the fact that they are hard to deal with.

In the mean time, #88 should solve this.

**Comment by loilo** [comment]
Thanks! 🙂
