### ISSUE TITLE
Unused global variable when using list

### ISSUE THREAD

**Issue by kkmuffme** [sirbrillig/phpcs-variable-analysis#89]
```
function abc() {
    global $test;
    list( $test, $example ) = my_function( $_POST );

    return $example;
}
```

will report:
Unused global variable $test.

But it isn't unused, since we assign a new value to it.

**Comment by sirbrillig** [comment]
This sounds very similar to #81, but perhaps it isn't covered since the assignment is done via list assignment.

**Comment by kkmuffme** [comment]
Yes thanks. Issue is fixed there.

**Comment by sirbrillig** [comment]
I added 8611e834169bead3b602ff70a1b9ed319c5de7a3 to make sure the case you mentioned above is covered by tests. Please let me know if you find a problem with it!
